### ISSUE TITLE
Is it possible to use this lib with react-native?

### ISSUE THREAD

**Issue by rg4real** [gogins/csound-extended#106]
It is extremely cool to see WASM support.

Is it possible to use this lib with react-native?

**Comment by gogins** [comment]
Sorry for the delay in getting to this issue.

I haven't used react-native, but from what I can tell, you write JavaScript and then it is compiled to code that is native for Android or iOS, is that correct?

If that is so, then there may be two options for using Csound in a react-native app.

- You can use the WebAssembly build but you would not have access to the WebAssembly instance of Csound until your app had loaded on the target device and then loaded the WebAssembly module.

- You can use the native build of Csound for Android or for iOS, which has a JavaScript interface. This actually makes more sense to me. For details on how to load the Csound object in an Android application, look at the example project here: https://github.com/strapparts/CSound-Android. I don't how much of this would carry over to react-native but I imagine something like this must be possible.
