### ISSUE TITLE
where is csound-extended-wasm-version.zip ?

### ISSUE THREAD

**Issue by xenophoria** [gogins/csound-extended#111]
Hi Michael,

I am trying to use WebAssembly for a webpage where visitors experiment with short audio examples before they download my [iOS concert music app](https://www.youtube.com/watch?v=gfaZly6dhQA) (Steven Yi and John ffitch already know about this). 

I noticed in the git **readme.md** file for csound-extended-wasm under **## installation**, it says 

`“Download `csound-extended-wasm-version.zip` from the release page here. Unzip it and it is ready to use”. `

The name of the zip file is highlighted but the link seems dead. And I can’t find a file by that name in the file system I downloaded from the git.

I suspect **csound-extended-wasm-version.zip** might be a zipped version of the WASM Csound module that browsers seem to wait for (indefinitely) when I try to launch 

`file:///Users/gs/Downloads/csound-extended-develop/WebAssembly/examples/minimal_wasm.html`

or try to run [https://waaw.csound.com/midi.html](https://waaw.csound.com/midi.html) offline.

Where can I find the WASM Csound module and is this “ready to use” off-line or does it need to be compiled locally ?

Greg S

**Comment by gogins** [comment]
I apologize for taking so long to respond to this issue.

That is just a filename, not a link. Currently the actual download link is https://github.com/gogins/csound-extended/releases/download/v1.3.5.1/csound-extended-wasm-1.0.2.zip. I will update the README.md to clarify this.
