### ISSUE TITLE
Problems/bugs with csound app for android

### ISSUE THREAD

**Issue by rawdani** [gogins/csound-extended#132]
Dear csound community,

I just download csound for android and I am expecting issues with the app. I hope you can help.

At the moment I am unable to use the app to run my files. It works great with the examples provided but if I load a file of mine the app gives me the message at "Csound is starting...
setCsoundText..." in the message tab (there is a post here regarding this problem but the suggested solution does not work for me http://csound.1045644.n5.nabble.com/Csnd-Bug-report-Csound-Android-6-14-0-can-play-examples-but-not-the-same-example-loaded-from-csd-file-td5767780.html#a5767781). Moreover, if I do not try to load a file but simply cut and paste and then run it, the application crashes, it closes itself with no visible error message. Bottom line, I am unable to run my files.

Please let me know if you need further information of if I can help in any way.

Thanks.

**Comment by gogins** [comment]
When Csound starts up, it prints in the Messages tab the path in which the Csound for Android app is authorized to write files. Trying to save a file outside of this directory is forbidden by Android. Save your example to this directory, then open it again from that directory and try to run it. Let me know if this works or not.

**Comment by gogins** [comment]
Moved the app to its own repo.
