### ISSUE TITLE
Drop the csound-extended build of Csound for WebAssembly for the "canonical" one with an API wrapper

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#143]
This may or may not be possible. But if it is possible I should do it. _There is no point in doing this until the feature/webaudio branch of csound is merged._

- [x] Try building the "canonical" one. Actually no, **_use the packaged version_**.
- [ ] Try porting a few of of my real pieces to see what's missing in the "canonical" API. The cmask and scrims examples might be good choices.
- [ ] See what can be done with a **_pure JavaScript_** API wrapper.
- [ ] If it can be fixed up, deprecate my build and make the wrapper part of the csound-extended package.

**Comment by gogins** [comment]
I have pretty much done this. I have created an Emscript Embind binding for most of CsoundAC, and changed the CsoundAC design to more cleanly separate score generation from synthesis, so that for example a WebAssembly build of CsoundAC can generate scores for a NW.js build of Csound. 

No doubt small issues will continue to crop up for some time but I am closing the main issue now.

**Comment by gogins** [comment]
The CsoundObj API is not a mirror of CsoundThreaded as my API is. However, the CsoundObj API does now support running a csd or an orc either as a filepath or as text.

The CsoundObj API is implemented both as ScriptProcessorNode and as AudioWorklet.

I am checking how many plugin opcodes are supported. The build is small... CsoundObj contains the "sf" opcodes but not the "fluid" opcodes so I presume it lacks other plugins. I am looking at the source code...

As a workaround for async and/or API compatibility, it should be possible to store arguments and then execute all required steps in one call.

**Comment by gogins** [comment]
I'm waiting for the latest canonical WebAssembly build to be merged.

**Comment by gogins** [comment]
I am following the `feature/webaudio` branch of sound. This is looking much better. There is a close shadowing of the "C" Csound API. The function calls are async. The function names unfortunately are camel case. And they are static. Perhaps there are plans for a class wrapper. Also I do not see csoundCompileCsdText in the list of functions.

There is no urgency but I will keep following this and perhaps migrate to it at some point.

**Comment by gogins** [comment]
I am closing this now but I will, _perhaps_, reopen it when the feature/webaudio branch of csound is merged.

**Comment by gogins** [comment]
I am reopening this as a glance at the webaudio branch indicates maybe the API is closer to mine than I thought. I will try to adapt Scrims.html to use this.

**Comment by gogins** [comment]
On second thought, maybe not. The good news is that csoundCompileCsdText exists. The bad news is that camel case remains and so do differences in the semantics of the API (csoundStart also does Perform).

The use of wasmer is however very interesting.

**Comment by gogins** [comment]
The wasm branch of csound has now been merged with the develop branch. Csound's wasm browser API is here: https://github.com/csound/csound/tree/develop/wasm/browser. Aside from camel case the major issue appears to be the use of Promises to receive values from asynchronous functions, while my wasm Csound interface wraps the promises to produce synchronous API methods.

Upon reflection, having a consistent API across platforms is of course the correct approach and it's too bad @hlolli did not use it, but considering how much I use wasm versus Linux it is not worth my time to produce a wrapper.

I will therefore proceed to implement **_Scrims_** (or a new piece) using Csound's version of wasm, and then I will close this issue.

**Comment by hlolli** [comment]
csoundCompileCsdText works in C, but with javascript modules csound.csoundCompileCsdText would look silly. But I discussed this with other csounders long ago, and csound.compileCsdText conveys readability and is otherwise 1:1 consistent with the C api.

**Comment by hlolli** [comment]
Adding as well. The decision to use promises will allow for consistency, because to get the return values from workers, an asynchronous system is needed. Event based is one way, but it's less modern that promises. It's possible to not await the return values, but it would be relying on luck, the tests pass for the exact same code on 5 different combinations of worker/shared-array-buffer/createScriptProcessor/worklet, but without await, timing issues would arise and they would fail while some may still succeed.

**Comment by gogins** [comment]
The Emscripten build is not nearly as easy to use as csound-extended-wasm. I will not use this. I will wait and see what happens if there is a macOS binary release of csound/wasm, which I am not easily able to build on macOS, and reopen this issue at that time. Until then, I am using csound-extended-wasm which worked on macOS right out of the box.
