### ISSUE TITLE
Integrate with other open source algorithmic composition systems 

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#161]
Add better facilities for integrating CsoundAC with other open source algorithmic composition systems. I will start with Python, but there might be others. Other systems should be able both to receive events from CsoundAC, and to send events to CsoundAC. The model should be something like the `LispNode`, but the `Node` subclasses should be specialized for the composition system in question.

- [x] Identify systems. See the next comment.  For now, I am doing only those that can be implemented in Python.
- [x] Design pattern when CsoundAC is the host. Usually, it will suffice to provide a Python module that reads the output data of the other system and parses it note by note to append to a `csound::Score.`
- [x] Design patterns when other systems host CsoundAC. Usually, it will be necessary for the other system to provide some facility for reading in external score data. Usually, this will be a MIDI file.
- [x] Implementation.
- [x] Testing. I am testing basic functionality as I go.

The main motivation here is to use Xenakis sieves with the chord space stuff without having to re-invent the wheel.

**Comment by gogins** [comment]
I'm not necessarily going to do all of these, by any means! This is just to identify possibilities.

2. athenaCL (Python)
2. abjad (Python/Lilypond).
3. musx (Python).
4. music21 (Python).
5. Pure Data (C).
6. Common Music (Scheme).
7. Common Music (Common Lisp).
8. Open Music (Common Lisp, won't run in the CsoundAC process).
9. [mutwo](https://github.com/mutwo-org/mutwo) (Python).

**Comment by gogins** [comment]
Might be easier to port the sieve from something.

**Comment by znmeb** [comment]
@gogins Is there an implementation of the sieves in any language? I've got the book but don't recall ever seeing code other than what Xenakis himself or his students wrote.

**Comment by gogins** [comment]
At least music21, athenaCL, and I think SuperCollider.

Regards,
Mike

**Comment by znmeb** [comment]
I'll try SuperCollider first - I already have the build scripts for that. :-)

**Comment by gogins** [comment]
I have completed the facility for generating scores in athenaCL and using them in CsoundAC, as csound-extended/CsoundAC/athenacl-to-csoundac.py. I do not currently see how to go in the other direction, or if that would even be necessary.

**Comment by gogins** [comment]
Got the musx stuff working with just Csound. Now for CsoundAC.

**Comment by gogins** [comment]
Did musx_to_csound and musx_to_csoundac.

Installed abjad and music21.

**Comment by gogins** [comment]
In general, feeding CsoundAC scores to other systems would require those systems to already have in place some facility for reading external music. MIDI of course is the _lingua franca_.

**Comment by gogins** [comment]
Abjad uses only Lilypond for output.

Lilypond either engraves, or creates MIDI files, or does this text export:
```
http://lilypond.org/doc/v2.18/Documentation/notation/saving-music-events-to-a-file
```

**Comment by gogins** [comment]
For systems such as abjad, music21, and Lilypond, it is tedious to discover how to flatten the score and yet retain all the information that CsoundAC needs. For these systems, the CsoundAC ExternalNode can store a Python script and the inputs to the system, save the score as a MIDI file, and import the MIDI file into a CsoundAC Score.

**Comment by gogins** [comment]
I've taken this as far as I can consistent with continuing to compose. I am opening a separate issue for the inability to run nudruz with Embeddable Common Lisp.

**Comment by gogins** [comment]
For musx, fractional pitches are implemented using a master track with different pitch bends for different channels, then fractional pitches for actual instruments are divided between channels. This is awkward to say the least.

**Comment by gogins** [comment]
This will probably be an ongoing issue for a while.

**Comment by gogins** [comment]
I had a productive Zoom call with Rick Taube and played some stuff for him, which till now he has not heard because ctcsound is broken at this time for recent versions of Python.

I am closing this issue as @ricktaube says he will merge my Csound adapter code into musx. New issues will appear in @ricktaube/musx.
