### ISSUE TITLE
Polyphonic pitch tracking in Csound?

### ISSUE THREAD

**Issue by musicmichaelc** [gogins/csound-extended#167]
Hi, I wasn't sure where I could best ask this question *(my sincere apologies if  the issue tracker isn't the right place for questions like this)*.  

I've been looking for a way to track pitches (and their relative amplitudes) as played on a piano. Since there will often be several notes playing together on the piano, it would be quite useful to be able to track several pitches simultaneously. However, so far (after searching the internet as well as the Csound manuals) I was only able to find monophonic pitch tracking opcodes in Csound.  

Does Csound-extended by any chance include such a polyphonic pitch tracker, or is there perhaps some plugin or custom opcode to be found somewhere that would be capable of performing this task?

**Comment by gogins** [comment]
Thanks for your interest, but my repo does not offer this. Try asking on
the regular Csound users list at ***@***.***

Regards,
Mike

**Comment by musicmichaelc** [comment]
Ok---too bad, but thanks nevertheless. I'll continue to try my luck on the forum as you suggested.
