### ISSUE TITLE
UDP (maybe also OSC) not working on Csound for Android app

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#26]
From ErrorThink:

> The Csound for Android 6.11.0 app (currently in the Play Store) doesn't respond to UDP messages. No error message: It just doesn't listen.
> This following test works in the previous app: Csound for Android 6.09.0beta2
> To test: Run UDPlisten.csd in the app.
> 
> <CsoundSynthesizer>
> <CsOptions>
> -odac --port=8099 --nchnls=2 --0dbfs=1 --sample-rate=48000 --ksmps=64 --messagelevel=128
> </CsOptions>
> <CsInstruments>
> prints "started UDP csd\n"
> </CsInstruments>
> <CsScore>
> f0 300
> </CsScore>
> </CsoundSynthesizer>
> Save a a bit of orc code in a file called udptest.txt
> udptest.txt
> 
> Then in a terminal enter
> nc -u 127.0.0.1 8099 < udptest.txt
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by gogins** [comment]
I have made the build system changes suggested by @kunstmusik and used the test files supplied by ErrorThink. The files work as advertised on Linux but do not work on Android.

**Comment by gogins** [comment]
The sample, with 127.0.0.1 8809, does this work only on localhost, or also
across nodes in a subnet?

I will try the app which should obviate that.

Thanks,
Mike

**Comment by kunstmusik** [comment]
You should look up the IP for your Android device under network settings
and use that with the nc command.  For example, my Android device had
192.168.0.101, so I used that with nc from my desktop to send the txt to my
phone.

**Comment by gogins** [comment]
D'oh! Confused between multicast and UDP. Did as you suggested, the Csound for Android app worked with the sample files just the same as the desktop Csound. The typo made no difference but I will fix it anyway of course.

I will post a new .apk to the Play Store today with these fixes.
