### ISSUE TITLE
Some 'sliders' are cut off when rotated.

### ISSUE THREAD

**Issue by iamsudipbh** [gogins/csound-extended#33]
**Expected Behavior**
The app should have shown all the **sliders** in landscape mode.

**Actual Behavior**
But some of the **sliders** are cut off in landscape mode.

**How to reproduce**
 1. First download the app from F-Droid.
 2. Launch the app. You can see all the available sliders in portrait mode.
 3. Rotate the screen in landscape mode.
You can see some of the **sliders** are cut off when rotated.

 • App Version : 6.11.1
 • Operating System : Android 6.0
 • Device : Lava Iris 50

**Recording of the bug**
https://www.youtube.com/watch?v=Dlj63tJayFQ

**Comment by gogins** [comment]
I have disabled orientation by sensor if the widgets are visible. It remains for the other layout configurations.
