### ISSUE TITLE
App crash when try to view example options from user guide page

### ISSUE THREAD

**Issue by kr-nahid** [gogins/csound-extended#35]
#### Expected behavior
user should be able to view any example options from user guide page without crash

#### Actual behavior
app crash when try to view example options in user guide page . 

#### How to reproduce
* Download the app
* open it then click on 3 horizontal dots icon
* then click on user guide 
* then click on Examples and now click on any examples options
* and note the bug

> Browser :  Csound for Android 6.11.1
 Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=pDN1P4WtGOU

**Comment by gogins** [comment]
Thank you for logging this bug report. I can reproduce the issue and I will debug it soon.

**Comment by gogins** [comment]
Many solutions that I found online do not work. Examining the Google Chrome issues suggests that these have been disabled for security reasons. 

I will make my help into a document of some sort and open that by intent.

**Comment by gogins** [comment]
Changed the User Guide to a .pdf file that is opened by intent, not with a WebView. This means the Examples menu is no longer visible when reading the Guide. When the PDF activity is closed, Csound re-appears and the examples can be run,.
