### ISSUE TITLE
App crash when click on ok button for save as 

### ISSUE THREAD

**Issue by kr-nahid** [gogins/csound-extended#36]
#### Expected behavior
user should be able to stay in app when click on ok button for save as .

#### Actual behavior
App crash when click on ok button for save as .

#### How to reproduce
* download the app
* open it then click on save as
* then try to save csd in any folder
* and note the bug

> Browser : Csound for Android 6.11.1
 Operating system: android 5.1

#### Recording Of The Bug
https://www.youtube.com/watch?v=pJAIy2sQ-Ug

**Comment by gogins** [comment]
Thank you for your bug report. I can reproduce the problem. It is caused when the user saves a CSD file that does not exist. I will debug this and protect the app from crashing in this case, perhaps with an alert to the user that he or she has not yet created a CSD file.

**Comment by gogins** [comment]
Done as above suggested.
