### ISSUE TITLE
Port nudruz as an OpenMusic library

### ISSUE THREAD

**Issue by gogins** [gogins/csound-extended#47]
Get Drew Krause's `nudruz` code hosted here to run as an OpenMusic library.

**Comment by gogins** [comment]
There is a new implementation of OpenMusic called o7 but it is not backwardly compatible and is not "ready for production."

I am continuing with regular old OpenMusic.

**Comment by gogins** [comment]
I am having problems getting cm2 to load in OpenMusic. Not sure what to do.

What I did do is diff `https://svn.code.sf.net/p/commonmusic/code/branches/cm2` against `https://github.com/andersvi/cm2.git` and found no differences at all with respect to Lisp or Scheme source code.

The problem appears to be "polyfills" provided by Common Music that are not required by, or that conflict with, LispWorks.

**Comment by gogins** [comment]
As a separate matter, Common Music is now said to run in Embedded Common Lisp which raises the possibility of creating a set of Lisp opcodes for Csound, or embedding Lisp in CsoundAC.

**Comment by gogins** [comment]
I got one of my Csound examples for nudruz to run. To do:

1. See if I can run it in OpenMusic.
2. See if I can get the pre-requisites to load.

**Comment by gogins** [comment]
I think I can move all of `nudruz-load.lisp` into `nudruz.asd` and be up to date, Lisp-wise.

**Comment by gogins** [comment]
The `nudruz.asd` files work for SBCL. I now need to get it to work for OpenMusic.

**Comment by azimut** [comment]
Can the nyc talk be linked here?
http://files.meetup.com/1748515/Drew%20Krause%20slides.pdf
https://vimeo.com/54910233

**Comment by gogins** [comment]
Yes, and thanks.

Regards,
Mike

**Comment by gogins** [comment]
I fixed the cffi interface to use foreign strings. `nudruz` now loads using just `(asdf:make :nudruz)`.
Now, to get it working in OpenMusic.

**Comment by gogins** [comment]
Hypothesis: OpenMusic's built-in lispworks can't compile Lisp code, only load. Perhaps this is not compatible with ASDF.

**Comment by gogins** [comment]
![screenshot from 2018-08-31 10-35-48](https://user-images.githubusercontent.com/6325029/44918982-514bcb00-ad0a-11e8-89a3-2c834207b19c.png)

**Comment by gogins** [comment]
How to write libraries for OpenMusic: http://repmus.ircam.fr/openmusic/dev-resources/userlib.

Here, `nudruz` will depend upon `cm2`.

**Comment by gogins** [comment]
There's another issue I'm not sure about, `nudruz` is in the `cm` package, is it possible to load code for the `cm` package in OpenMusic?

**Comment by gogins** [comment]
Oh, and I forgot, Common Music now transpiles Scheme to Lisp while loading! Don't know if this will work, either, this might be a show-stopper.

**Comment by gogins** [comment]
I could go really nuts and put ECL inside OpenMusic!

**Comment by azimut** [comment]
would it help have cllib/clloc put as a optional dependency? All but spacegrp.lisp can work with just some cllib functions imported into nudruz.lisp. Then on the asd we can have two defsystem to support spacegrp.lisp if you have cllib.

**Comment by gogins** [comment]
Could you create another pull request?

Regards,
Mike

**Comment by gogins** [comment]
The real gating issue here is not `nudruz` but its foundation, Common Music 2, which requires ASDF compilation to turn Scheme code into Lisp objects. There is no point pursuing this issue further until ASDF is functional in Common Music, which evidently requires a working Lisp compiler.
