### ISSUE TITLE
Csound for Android app doesn't load files other than examples.

### ISSUE THREAD

**Issue by noisesmith** [gogins/csound-extended#83]
Using a Galaxy Note 9 with One UI Version 1.0 and Android version 9, Android security patch level March 1, 2019, Csound for Android version 6.12.0.

The examples load and play.

The "Save as..." button doesn't do anything.

I can open the example files in an external editor, but none of the edits are loaded back into Csound.

I can't use the file manager to send a file to Csound.

I can't open a file with the Open button in Csound (it opens a file chooser and lets me pick one, but doesn't load the file).

The result of this is that I can only run the examples, there's no series of actions that allows me to edit a file and then run it in the Csound app.

**Comment by ErrorThink** [comment]
This sounds similar to issue [https://github.com/gogins/csound-extended/issues/65](https://github.com/gogins/csound-extended/issues/65)
Was resolved by granting permissions.

**Comment by noisesmith** [comment]
I found that bug when checking if my issue was a duplicate. I should have mentioned this in my initial bug report.

I checked my app perms to make sure Csound had file permissions (it did), then I reinstalled in case some bad state came up, the app asked for permission to files and the mic when it first ran and I granted both.

There's at least something more complex than that specific file permission going on here.

By the way, thanks for making this app available, I liked being able to write and run csound synths on my mobile, and I hope we can make it work again.

**Comment by gogins** [comment]
Thanks for the additional info. It works fine for me, so please email me:

Your Csound app version from the Settings/Apps/Csound page. Mine: 6.12.2.

Your device vendor and model number from the Settings/About phone page.
Mine: Samsung SM-950U.

Your operating system version from the Settings/About phone/Software
information page. Mine: Android version 9.

Perhaps then I can debug in an emulator.

Regards,
Mike

**Comment by gogins** [comment]
Your setup has the same operating system, a newer model of the Galaxy Note (me, 8, you, 9), and an older version of the Csound App. I will download your version from the Play Store and try to reproduce the issue.

**Comment by gogins** [comment]
Version code of the current app in the Google Play Store is 18.

**Comment by gogins** [comment]
Please try:
Looking at your Android settings for Csound at Settings/Apps/com.csounds.csound6/Permissions and ensure that Microphone and Storage are enabled.
Ensure that you have a text editor that has permissions to access your storage.
There are default storage locations, SDCard/csd and SDCard/html. Did you look in these locations?

**Comment by noisesmith** [comment]
I've checked permissions, as mentioned above.

My text editor has storage permissions also.

The file browser for the "open" button lets me navigate to all these locations, but doesn't open files when I click to select them - if an example was open it's still open, if not there's no document just as before.

For version, the UI says 6.12.0, but under system app settings it shows up as 6.12.2

model: SM-N960U1
hardware version: REV1.1
android version 9, one ui version 1.0

I just opted into the "beta", maybe that will help me get a newer version.

I have work profile turned on (it's a security feature that isolates work applications, required by my workplace), but as far as I know that shouldn't effect any of this.

**Comment by gogins** [comment]
I have built and signed the latest version of the Csound for Android app, and you can download it from here: https://github.com/gogins/csound-extended/releases/tag/v1.3.0beta.

**Comment by gogins** [comment]
I have downloaded the emulator skin for the Galaxy Note 9 from Samsung.

I am downloading the emulator for Android 9 for the x86_64 architecture. 

This seems to be as close as I can come to debugging on your device. If the new Csound for Android app doesn't work for you, I will try the emulator.

**Comment by gogins** [comment]
Did you try the new version of the app from GitHub?

**Comment by noisesmith** [comment]
I just tried the version you posted on the mailing list, and it resolves my issues!

Convenient to have a simple editor in the app too.

Thanks for sticking with this, I'd almost compromised on something less useful.

**Comment by gogins** [comment]
Thanks for your prompt and helpful feedback.

Regards,
Mike
